title: Welcome to my Portfolio.
description: Welcome to my Data Analytics Portfolio.
![Image](https://scontent.fbkk25-1.fna.fbcdn.net/v/t39.30808-6/257764328_10158425099057919_4873678565206625421_n.jpg?_nc_cat=105&ccb=1-5&_nc_sid=730e14&_nc_eui2=AeH1ArLuxY7MGqW_vkAdhRaz5wVaJ8A6vs3nBVonwDq-zTGlO5wyLqKKXVYWiPOvwEk&_nc_ohc=6SZwFVrAdv0AX_oNQS7&_nc_oc=AQmfKahioA0HRjN3wSqd_eQNbHk4s0x3YhKUEDUKYC4A1bhOFti7Fl8IuQ_Mf4ZWOsQ&_nc_ht=scontent.fbkk25-1.fna&oh=357c97d5e933109eaab1242d1cf32065&oe=619AEBE5)


theme: jekyll-theme-minimal
