title: My Portfolio
logo: /img/logo.png
description: Pakkawat Komonman<br />Phone 084-342-6242<br />E-mail pakkawatko@gmail.com<br />Sr.Process Engineer and Data Analyst.<br /><br /><br /><br />
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
