title: Pakkawat Komonman
logo: /img/logo.png
description: [Phone] 084-342-6242<br />[E-mail] pakkawatko@gmail.com<br />Sr.Process Engineer and Data Analyst.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
