title: My Portfolio
logo: /img/logo.png
description: PAKKAWAT KOMONMAN<br />PHONE: 084-342-6242<br />EMAIL: pakkawatko@gmail.com<br />Sr.Process Engineer and Data Analyst.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
